/* Generated by           cobc 3.3-dev.0 */
/* Generated from         temp_compile.cbl */
/* Generated at           èþë 22 2025 11:26:01 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        cobc -g -x temp_compile.cbl */

/* Program local variables for 'CONDITIONALS' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[9] __attribute__((aligned));	/* NUM1 */
static cob_u8_t	b_18[9] __attribute__((aligned));	/* NUM2 */
static cob_u8_t	b_19[5] __attribute__((aligned));	/* NUM3 */
static cob_u8_t	b_20[6] __attribute__((aligned));	/* NUM4 */
static cob_u8_t	b_21[9] __attribute__((aligned));	/* NEG-NUM */
static cob_u8_t	b_22[9] __attribute__((aligned));	/* CLASS1 */
static cob_u8_t	b_23[3] __attribute__((aligned));	/* CHECK-VAL */

/* End of local data storage */


/* Fields (local) */
static cob_field f_19	= {5, b_19, &a_2};	/* NUM3 */
static cob_field f_20	= {6, b_20, &a_3};	/* NUM4 */
static cob_field f_23	= {3, b_23, &a_4};	/* CHECK-VAL */

/* End of fields */

