/* Generated by           cobc 3.3-dev.0 */
/* Generated from         temp_compile.cbl */
/* Generated at           èþë 22 2025 11:26:01 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        cobc -g -x temp_compile.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   5,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   6,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   3,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {20, (cob_u8_ptr)"IN LOOP 1 - IF BLOCK", &a_1};
static const cob_field c_2	= {20, (cob_u8_ptr)"IN LOOP 2 - IF BLOCK", &a_1};
static const cob_field c_3	= {22, (cob_u8_ptr)"IN LOOP 2 - ELSE BLOCK", &a_1};
static const cob_field c_4	= {21, (cob_u8_ptr)"IN LOOP 1 -ELSE BLOCK", &a_1};
static const cob_field c_5	= {12, (cob_u8_ptr)"PASSED WITH ", &a_1};
static const cob_field c_6	= {7, (cob_u8_ptr)" MARKS.", &a_1};
static const cob_field c_7	= {12, (cob_u8_ptr)"FAILED WITH ", &a_1};
static const cob_field c_8	= {16, (cob_u8_ptr)"NUM1 LESS THAN 2", &a_1};
static const cob_field c_9	= {17, (cob_u8_ptr)"NUM1 LESS THAN 19", &a_1};
static const cob_field c_10	= {19, (cob_u8_ptr)"NUM1 LESS THAN 1000", &a_1};


#define cob_nop	if (!module) cob_nop

