/* Generated by           cobc 3.3-dev.0 */
/* Generated from         temp_compile.cbl */
/* Generated at           июл 24 2025 10:17:31 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        cobc -g -x -IC:\msys64\mingw64\include -LC:\msys64\mingw64\lib -lgmp temp_compile.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   2,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {17, (cob_u8_ptr)"Введите ваше имя:", &a_1};
static const cob_field c_2	= {38, (cob_u8_ptr)"Введите год рождения (например, 1990):", &a_1};
static const cob_field c_3	= {8, (cob_u8_ptr)"Привет, ", &a_1};
static const cob_field c_4	= {7, (cob_u8_ptr)"! Тебе ", &a_1};
static const cob_field c_5	= {5, (cob_u8_ptr)" лет.", &a_1};


#define cob_nop	if (!module) cob_nop

