/* Generated by           cobc 3.3-dev.0 */
/* Generated from         temp_compile.cbl */
/* Generated at           èþë 24 2025 10:17:31 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        cobc -g -x -IC:\msys64\mingw64\include -LC:\msys64\mingw64\lib -lgmp temp_compile.cbl */

/* Program local variables for 'AGE-CALCULATOR' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[20] __attribute__((aligned));	/* USER-NAME */
static cob_u8_t	b_18[4] __attribute__((aligned));	/* BIRTH-YEAR */
static cob_u8_t	b_19[4] __attribute__((aligned));	/* CURRENT-YEAR */
static cob_u8_t	b_20[2] __attribute__((aligned));	/* AGE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {20, b_17, &a_2};	/* USER-NAME */
static cob_field f_18	= {4, b_18, &a_3};	/* BIRTH-YEAR */
static cob_field f_19	= {4, b_19, &a_3};	/* CURRENT-YEAR */
static cob_field f_20	= {2, b_20, &a_4};	/* AGE */

/* End of fields */

