/* Generated by           cobc 3.3-dev.0 */
/* Generated from         temp_compile.cbl */
/* Generated at           èþë 22 2025 11:26:01 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        cobc -g -x temp_compile.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"temp_compile.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"èþë 22 2025 11:26:01"
#define  COB_MODULE_DATE		20250722
#define  COB_MODULE_TIME		112601

/* Global variables */
#include "temp_compile.c.h"

/* Function prototypes */

static int		CONDITIONALS ();
static int		CONDITIONALS_ (const int);
static void		CONDITIONALS_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CONDITIONALS ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'CONDITIONALS' */

/* ENTRY 'CONDITIONALS' */

static int
CONDITIONALS ()
{
  return CONDITIONALS_ (0);
}

static int
CONDITIONALS_ (const int entry)
{
  /* Program local variables */
  #include "temp_compile.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 26        : Entry     CONDITIONALS            : temp_compile.cbl */
  l_2:;
#line 26 "temp_compile.cbl"
  ENTRY_CONDITIONALS:	cob_nop ();
#line 105 "temp_compile.c"

  /* Line: 26        : MOVE               : temp_compile.cbl */
#line 26 "temp_compile.cbl"
  cob_nop ();
#line 110 "temp_compile.c"
  memcpy (b_17, "000000025", 9);
  memcpy (b_19, "00025", 5);

  /* Line: 27        : MOVE               : temp_compile.cbl */
#line 27 "temp_compile.cbl"
  cob_nop ();
#line 117 "temp_compile.c"
  memcpy (b_18, "000000015", 9);
  memcpy (b_20, "000015", 6);

  /* Line: 30        : IF                 : temp_compile.cbl */
#line 30 "temp_compile.cbl"
  cob_nop ();
#line 124 "temp_compile.c"
  if (((int)memcmp (b_17, b_18, 9) > 0))
  {

    /* Line: 31        : DISPLAY            : temp_compile.cbl */
#line 31 "temp_compile.cbl"
    cob_nop ();
#line 131 "temp_compile.c"
    cob_display (0, 1, 1, &c_1);

    /* Line: 32        : IF                 : temp_compile.cbl */
#line 32 "temp_compile.cbl"
    cob_nop ();
#line 137 "temp_compile.c"
    if (((int)cob_numeric_display_cmp (&f_19, &f_20) == 0))
    {

      /* Line: 33        : DISPLAY            : temp_compile.cbl */
#line 33 "temp_compile.cbl"
      cob_nop ();
#line 144 "temp_compile.c"
      cob_display (0, 1, 1, &c_2);
    }
    else
    {
      /* ELSE */

      /* Line: 35        : DISPLAY            : temp_compile.cbl */
#line 35 "temp_compile.cbl"
      cob_nop ();
#line 154 "temp_compile.c"
      cob_display (0, 1, 1, &c_3);
    }
  }
  else
  {
    /* ELSE */

    /* Line: 38        : DISPLAY            : temp_compile.cbl */
#line 38 "temp_compile.cbl"
    cob_nop ();
#line 165 "temp_compile.c"
    cob_display (0, 1, 1, &c_4);
  }

  /* Line: 43        : MOVE               : temp_compile.cbl */
#line 43 "temp_compile.cbl"
  cob_nop ();
#line 172 "temp_compile.c"
  memcpy (b_23, "065", 3);

  /* Line: 44        : IF                 : temp_compile.cbl */
#line 44 "temp_compile.cbl"
  cob_nop ();
#line 178 "temp_compile.c"
  if ((((int)cob_cmp_numdisp (b_23, 3, COB_S64_C(41), 0) >= 0) && 
      ((int)cob_cmp_numdisp (b_23, 3, COB_S64_C(100), 0) <= 0)))
  {

    /* Line: 45        : DISPLAY            : temp_compile.cbl */
#line 45 "temp_compile.cbl"
    cob_nop ();
#line 186 "temp_compile.c"
    cob_display (0, 1, 3, &c_5, &f_23, &c_6);
  }

  /* Line: 46        : IF                 : temp_compile.cbl */
#line 46 "temp_compile.cbl"
  cob_nop ();
#line 193 "temp_compile.c"
  if ((((int)cob_numeric_display_cmp_zero (&f_23) >= 0) && 
      ((int)cob_cmp_numdisp (b_23, 3, COB_S64_C(40), 0) <= 0)))
  {

    /* Line: 47        : DISPLAY            : temp_compile.cbl */
#line 47 "temp_compile.cbl"
    cob_nop ();
#line 201 "temp_compile.c"
    cob_display (0, 1, 3, &c_7, &f_23, &c_6);
  }

  /* Line: 50        : EVALUATE           : temp_compile.cbl */
#line 50 "temp_compile.cbl"
  cob_nop ();
#line 208 "temp_compile.c"

  /* Line: 51        : WHEN               : temp_compile.cbl */
#line 51 "temp_compile.cbl"
  cob_nop ();
#line 213 "temp_compile.c"

  if (((int)cob_cmp_numdisp (b_17, 9, COB_S64_C(2), 0) < 0))
  {

    /* Line: 52        : DISPLAY            : temp_compile.cbl */
#line 52 "temp_compile.cbl"
    cob_nop ();
#line 221 "temp_compile.c"
    cob_display (0, 1, 1, &c_8);
    goto l_5;
  }

  /* Line: 53        : WHEN               : temp_compile.cbl */
#line 53 "temp_compile.cbl"
  cob_nop ();
#line 229 "temp_compile.c"

  if (((int)cob_cmp_numdisp (b_17, 9, COB_S64_C(19), 0) < 0))
  {

    /* Line: 54        : DISPLAY            : temp_compile.cbl */
#line 54 "temp_compile.cbl"
    cob_nop ();
#line 237 "temp_compile.c"
    cob_display (0, 1, 1, &c_9);
    goto l_5;
  }

  /* Line: 55        : WHEN               : temp_compile.cbl */
#line 55 "temp_compile.cbl"
  cob_nop ();
#line 245 "temp_compile.c"

  if (((int)cob_cmp_numdisp (b_17, 9, COB_S64_C(1000), 0) < 0))
  {

    /* Line: 56        : DISPLAY            : temp_compile.cbl */
#line 56 "temp_compile.cbl"
    cob_nop ();
#line 253 "temp_compile.c"
    cob_display (0, 1, 1, &c_10);
    goto l_5;
  }

  /* End EVALUATE */
  l_5:;

  /* Line: 58        : STOP RUN           : temp_compile.cbl */
#line 58 "temp_compile.cbl"
  cob_nop ();
#line 264 "temp_compile.c"
  cob_stop_run (b_2);

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  CONDITIONALS_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field NUM1 */
#line 8 "temp_compile.cbl"
  cob_nop ();
#line 317 "temp_compile.c"
  memset (b_17, (unsigned char)'0', 9);

  /* initialize field NUM2 */
#line 9 "temp_compile.cbl"
  cob_nop ();
#line 323 "temp_compile.c"
  memset (b_18, (unsigned char)'0', 9);

  /* initialize field NUM3 */
#line 10 "temp_compile.cbl"
  cob_nop ();
#line 329 "temp_compile.c"
  memset (b_19, (unsigned char)'0', 5);

  /* initialize field NUM4 */
#line 11 "temp_compile.cbl"
  cob_nop ();
#line 335 "temp_compile.c"
  memset (b_20, (unsigned char)'0', 6);

  /* initialize field NEG-NUM */
#line 14 "temp_compile.cbl"
  cob_nop ();
#line 341 "temp_compile.c"
  memcpy (b_21, "00000123t", 9);

  /* initialize field CLASS1 */
#line 16 "temp_compile.cbl"
  cob_nop ();
#line 347 "temp_compile.c"
  memcpy (b_22, "ABCD     ", 9);

  /* initialize field CHECK-VAL */
#line 19 "temp_compile.cbl"
  cob_nop ();
#line 353 "temp_compile.c"
  memset (b_23, (unsigned char)'0', 3);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CONDITIONALS' */

/* Initialize module structure for CONDITIONALS */
static void CONDITIONALS_module_init (cob_module *module)
{
  module->module_name = "CONDITIONALS";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())CONDITIONALS;
  module->module_cancel.funcptr = (void *(*)())CONDITIONALS_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

