/* Generated by           cobc 3.3-dev.0 */
/* Generated from         temp_compile.cbl */
/* Generated at           èþë 24 2025 10:17:31 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        cobc -g -x -IC:\msys64\mingw64\include -LC:\msys64\mingw64\lib -lgmp temp_compile.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"temp_compile.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"èþë 24 2025 10:17:31"
#define  COB_MODULE_DATE		20250724
#define  COB_MODULE_TIME		101731

/* Global variables */
#include "temp_compile.c.h"

/* Function prototypes */

static int		AGE__CALCULATOR ();
static int		AGE__CALCULATOR_ (const int);
static void		AGE__CALCULATOR_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (AGE__CALCULATOR ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'AGE-CALCULATOR' */

/* ENTRY 'AGE__CALCULATOR' */

static int
AGE__CALCULATOR ()
{
  return AGE__CALCULATOR_ (0);
}

static int
AGE__CALCULATOR_ (const int entry)
{
  /* Program local variables */
  #include "temp_compile.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 12        : Entry     AGE-CALCULATOR          : temp_compile.cbl */
  l_2:;
#line 12 "temp_compile.cbl"
  ENTRY_AGE__CALCULATOR:	cob_nop ();
#line 109 "temp_compile.c"

  /* Line: 12        : DISPLAY            : temp_compile.cbl */
#line 12 "temp_compile.cbl"
  cob_nop ();
#line 114 "temp_compile.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 13        : ACCEPT             : temp_compile.cbl */
#line 13 "temp_compile.cbl"
  cob_nop ();
#line 120 "temp_compile.c"
  cob_accept (&f_17);

  /* Line: 15        : DISPLAY            : temp_compile.cbl */
#line 15 "temp_compile.cbl"
  cob_nop ();
#line 126 "temp_compile.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 16        : ACCEPT             : temp_compile.cbl */
#line 16 "temp_compile.cbl"
  cob_nop ();
#line 132 "temp_compile.c"
  cob_accept (&f_18);

  /* Line: 18        : COMPUTE            : temp_compile.cbl */
#line 18 "temp_compile.cbl"
  cob_nop ();
#line 138 "temp_compile.c"
  cob_decimal_set_field (d_0, &f_19);
  cob_decimal_set_field (d_1, &f_18);
  cob_decimal_sub (d_0, d_1);
  cob_decimal_get_field (d_0, &f_20, 0);

  /* Line: 20        : DISPLAY            : temp_compile.cbl */
#line 20 "temp_compile.cbl"
  cob_nop ();
#line 147 "temp_compile.c"
  cob_display (0, 1, 5, &c_3, &f_17, &c_4, &f_20, &c_5);

  /* Line: 22        : STOP RUN           : temp_compile.cbl */
#line 22 "temp_compile.cbl"
  cob_nop ();
#line 153 "temp_compile.c"
  cob_stop_run (b_2);

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  AGE__CALCULATOR_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field USER-NAME */
#line 6 "temp_compile.cbl"
  cob_nop ();
#line 206 "temp_compile.c"
  memset (b_17, (unsigned char)' ', 20);

  /* initialize field BIRTH-YEAR */
#line 7 "temp_compile.cbl"
  cob_nop ();
#line 212 "temp_compile.c"
  memset (b_18, (unsigned char)'0', 4);

  /* initialize field CURRENT-YEAR */
#line 8 "temp_compile.cbl"
  cob_nop ();
#line 218 "temp_compile.c"
  memcpy (b_19, "2025", 4);

  /* initialize field AGE */
#line 9 "temp_compile.cbl"
  cob_nop ();
#line 224 "temp_compile.c"
  memset (b_20, (unsigned char)'0', 2);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'AGE-CALCULATOR' */

/* Initialize module structure for AGE-CALCULATOR */
static void AGE__CALCULATOR_module_init (cob_module *module)
{
  module->module_name = "AGE-CALCULATOR";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())AGE__CALCULATOR;
  module->module_cancel.funcptr = (void *(*)())AGE__CALCULATOR_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

